[31기 박경서] Add: 메뉴 상세페이지 레이아웃 구현 및 컴포넌트화
wecode-bootcamp-korea/31-1st-Dont-SOT-frontend pull request #2
Opened 2022-03-29 07:31 UTC by charile1

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-03-31 06:17 UTC, charile1 commented on src/pages/Menu/Components/Aside/Aside.js
> +  const navigate = useNavigate();
navigate 사용할 것임

2022-04-01 16:53 UTC, ghost commented on src/pages/Menu/Components/CategoryList/Item.js
> +  console.log(params);
__[ESLint]__ Unexpected console statement. ([view](https://sider.review/gh/repos/474886355/pulls/2#issue-6845150))

<details>

| Rule | Severity | Recommended |
| ---- | -------- | ----------- |
| `no-console` | `warn` | No |

References:
- <https://eslint.org/docs/rules/no-console>

You can [close this issue](https://sider.review/gh/repos/474886355/pulls/2#issue-6845150) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).

</details>

2022-04-01 16:53 UTC, ghost commented on src/pages/Menu/Components/ProductSpec/ProductSpec.js
> +  console.log(params);
__[ESLint]__ Unexpected console statement. ([view](https://sider.review/gh/repos/474886355/pulls/2#issue-6845151))

<details>

| Rule | Severity | Recommended |
| ---- | -------- | ----------- |
| `no-console` | `warn` | No |

References:
- <https://eslint.org/docs/rules/no-console>

You can [close this issue](https://sider.review/gh/repos/474886355/pulls/2#issue-6845151) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).

</details>

2022-04-01 16:53 UTC, ghost commented on src/pages/Menu/MenuList/MenuList.js
> +  console.log(params); //params나왓으니까 이거 api 주소 넣어보기
__[ESLint]__ Unexpected console statement. ([view](https://sider.review/gh/repos/474886355/pulls/2#issue-6845152))

<details>

| Rule | Severity | Recommended |
| ---- | -------- | ----------- |
| `no-console` | `warn` | No |

References:
- <https://eslint.org/docs/rules/no-console>

You can [close this issue](https://sider.review/gh/repos/474886355/pulls/2#issue-6845152) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).

</details>

2022-04-01 16:53 UTC, ghost commented on src/pages/Menu/MenuList/MenuSpec.js
> +  console.log(params);
__[ESLint]__ Unexpected console statement. ([view](https://sider.review/gh/repos/474886355/pulls/2#issue-6845153))

<details>

| Rule | Severity | Recommended |
| ---- | -------- | ----------- |
| `no-console` | `warn` | No |

References:
- <https://eslint.org/docs/rules/no-console>

You can [close this issue](https://sider.review/gh/repos/474886355/pulls/2#issue-6845153) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).

</details>

2022-04-01 16:53 UTC, ghost commented on src/pages/Menu/Components/CategoryList/Item.js
> +  const { id, categoryItem, parameter } = props;
__[ESLint]__ 'parameter' is assigned a value but never used. ([view](https://sider.review/gh/repos/474886355/pulls/2#issue-6845154))

<details>

| Rule | Severity | Recommended |
| ---- | -------- | ----------- |
| `no-unused-vars` | `warn` | Yes |

References:
- <https://eslint.org/docs/rules/no-unused-vars>

You can [close this issue](https://sider.review/gh/repos/474886355/pulls/2#issue-6845154) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).

</details>

2022-04-01 16:53 UTC, ghost commented on src/pages/Menu/Components/Card/Card.js
> +    <>
__[ESLint]__ Fragments should contain more than one child - otherwise, there‘s no need for a Fragment at all. ([view](https://sider.review/gh/repos/474886355/pulls/2#issue-6845156))

<details>

| Rule | Severity | Recommended |
| ---- | -------- | ----------- |
| `react/jsx-no-useless-fragment` | `warn` | No |

References:
- <https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/jsx-no-useless-fragment.md>

You can [close this issue](https://sider.review/gh/repos/474886355/pulls/2#issue-6845156) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).

</details>

2022-04-05 04:10 UTC, we-dohyeon reviewed
전체적으로 구조가 정말 깔끔하네요! 수고하셨습니다!
리뷰 반영해주세요~

2022-04-05 04:10 UTC, we-dohyeon commented on src/pages/Menu/Components/Aside/Aside.js
> +            {category.map(category => {
```suggestion
            {category.map({id, categoryName, categoryList} => {
```
경서님! 위와 같이 구조분해할당 사용하시면 가독성이 더 올라가겠네요!

2022-04-05 04:10 UTC, we-dohyeon commented on src/pages/Menu/Components/CategoryList/Item.js
> +    window.location.reload();
새로고침을 사용하는 이유가 있을까요?

2022-04-05 04:10 UTC, we-dohyeon commented on src/pages/Menu/Components/ProductSpec/Components/Allergy.js
> +        </div>
작업이 완료되면 컴포넌트 재사용을 통해 리팩토링 진행해주세요!

2022-04-05 04:58 UTC, charile1 commented on src/pages/Menu/Components/CategoryList/Item.js
> +import { useParams } from 'react-router-dom';
삭제완료

2022-04-05 04:58 UTC, charile1 commented on src/pages/Menu/Components/CategoryList/Item.js
> +import { useLocation } from 'react-router-dom';
삭제완료

2022-04-05 04:58 UTC, charile1 commented on src/pages/Menu/Components/CategoryList/Item.js
> +import { Link } from 'react-router-dom';
삭제완료

2022-04-05 04:58 UTC, charile1 commented on src/pages/Menu/MenuList/MenuBox.js
> +  }, [category]);
카테고리 state가 변경될때마다 fetch를 해야해서 의존성배열로 넣어줬는데 뭐가 문제인지 모르겠습니다..!

2022-04-05 04:58 UTC, charile1 commented on src/pages/Menu/Components/Card/Card.js
> +    <>
Fragments 하위에 바로 product.map가 나와서 Fragments 삭제 시 에러 발생해서 지우지 않았습니다!

2022-04-05 04:58 UTC, charile1 commented on src/pages/Menu/Components/ProductSpec/ProductSpec.js
> +    <>
삭제완료

2022-04-05 04:58 UTC, charile1 commented on src/pages/Menu/Components/CategoryList/Item.js
> +    window.location.reload();
원래는 새로고침을 사용하지 않고 <Menubox.js> 컴포넌트 25번째줄에서 category state 가 변경될 때마다 렌더링을 하기위해서 의존성 배열에 state를 넣어줬었는데 무한 렌더링이 되어서 fetch 요청을 무한으로 하길래 일단 빼주고 새로고침으로 구현하였습니다. 의존성 배열을 [] 아예 비워놓으면 첫 렌더링시에만 되어서 카테고리 탭을 누를때마다 화면 렌더링이 되지않고, state를 넣어놓으면 무한렌더링이 되는데 어떻게 해결할 수 있을까요..?

2022-04-05 04:58 UTC, charile1 commented on src/pages/Menu/Components/ProductSpec/Components/Allergy.js
> +        </div>
이 부분은 제가 레이아웃 작업을 하고 merge 되면 브랜치 따로 생성해서 홍두현님이 컴포넌트 사용해서 작업하시기로 했는데 merge를 위해서 이 부분 내용을 아예 빼는게 좋을까요?

2022-04-05 04:58 UTC, charile1 commented on src/pages/Menu/MenuList/MenuBox.js
> +  }, []);
fetchData 함수를 useEffect 바깥에서 선언해서 나온 사이더 에러 같습니다. 해결해야하는 문제인가요?

2022-04-05 04:58 UTC, charile1 commented on src/pages/Menu/Components/ProductSpec/ProductSpec.js
> +  const fetchData = () => {
fetchData 함수를 useEffect 바깥에서 선언해서 나온 사이더 에러 같습니다. 해결해야하는 문제인가요?

2022-04-05 04:58 UTC, charile1 commented on src/pages/Menu/Products.js
> +    <>
프레그먼트 삭제 완료

2022-04-05 06:09 UTC, we-dohyeon commented on src/pages/Menu/Components/ProductSpec/Components/Allergy.js
> +        </div>
아 그러면 그대로 진행해주세요!

2022-04-05 07:34 UTC, younuk23 requested changes
LGTM 👍
마이너한 수정사항 하나 남겼습니다.
확인 및 수정 진행해주시고 컨플릭 해결해주세요!

2022-04-05 07:34 UTC, younuk23 commented on src/pages/Menu/Components/Aside/Aside.scss
> +    // min-height: 400px;
불필요한 주석은 삭제해주세요!
코드가 주석처리된 채로 남아있다면 필요한 상황에 제대로 사용되거나 삭제되는 일은 거의 없고 결국 계속 남아있게 됩니다.
그러다보면 이제 작성한 사람이 아닌 다른 개발자는 필요한 코드라서 주석처리한게 아닐까? 라는 생각으로 지우지 못하고
결국 그 누구도 왜 있는지는 모르면서 계속 남아있는 불필요한 레거시가 되어버립니다! 
따라서 반드시 필요한 경우가 아니면 코드를 주석처리하기보다는 삭제해주시고 만약 다시 보고싶다면 커밋 이력에 잘 남겨뒀다가 원하는 시점에 다시 보면 됩니다!

2022-04-05 11:50 UTC, charile1 commented on src/pages/Menu/Components/CategoryList/Item.js
> +    window.location.reload();
무한루프되는 이유를 깨달았고 의존성 배열에 category state가 아닌 location.search를 넣어서 해결하였습니다.

2022-04-05 11:50 UTC, charile1 commented on src/pages/Menu/Components/Aside/Aside.js
> +            {category.map(category => {
네! 수정하였습니다!

2022-04-05 11:50 UTC, charile1 commented on src/pages/Menu/Components/Card/Card.js
> +    <>
코드 수정해서  프레그 먼트 삭제 완료

2022-04-06 05:42 UTC, sodalite1204 reviewed
리뷰 반영해주세요:)

2022-04-06 05:42 UTC, sodalite1204 commented on src/pages/Menu/Components/Card/Card.js
> +  const { product } = props;
```suggestion
const Card = ({ product })=> {
```
매개변수 자리에서 바로 구조분해 할당 가능합니다!

2022-04-06 05:42 UTC, sodalite1204 commented on src/pages/Menu/Components/Card/Card.js
> +                });
두번째 인자로 
```jsx
{
    state: props,
                });
```
를 사용하신 이유가 있나요?
단순히 생각했을 때 상품리스트 클릭 -> navigate(`/products/${data.id}`)로 이동
-> 상품 상세페이지에서는 바뀐 URl에 맞춰서 parmas id 값 받음 -> 백엔드에 데이터 요청
이여서 굳이 props로 넘겨줄 필요가 없는 부분인 것 같습니다!

2022-04-06 05:42 UTC, sodalite1204 commented on src/pages/Menu/Components/ProductSpec/ProductSpec.js
> +  const params = useParams();
```suggestion
  const { id } = useParams();
```
Router에서 선언한 변수값만 객체로 받아오기 때문에 바로 구조분해 할당해서 사용하는게 더 가독성이 좋습니다.
아래에서 사용한 params.id 도 맞춰서 바꿔주세요.

2022-04-06 05:42 UTC, sodalite1204 commented on src/pages/Menu/Components/ProductSpec/ProductSpec.js
> +                </a>
`<a>` tag는 url을 변경하면서 새롭게 서버에 html 파일을 요청해서 받아와서 브라우저에 내용을 보여주는 동작을 합니다, 반면에 `<Link>` 컴포넌트는 url은 변경하지만 새롭게 서버에 파일을 요청하는 것이 아니라 react-router-dom을 이용해서 내부적으로 보여지는 컴포넌트만 교체해줍니다. 

CRA로 만든 프로젝트는 SPA로서 html이 하나고 그 안에 보여주는 내용만 계속해서 바꿔주는 식으로 동작합니다.

서버에 새롭게 요청을 하지않고 화면을 그려주는 Client Side Rendering(CSR)을 수행하기 위해서 `<Link>` 컴포넌트 사용해주세요. 우리의 React 어플리케이션이 아닌 외부 링크로 이동할 경우에는 실제로 새롭게 서버에 요청을해서 html 파일을 받아와야하기에 `<a>` tag 사용해주시면 됩니다.

SPA의 개념에 대한 이해가 부족하다면 3주차에 배운 React Router & Sass 세션 내용 참고해주세요

2022-04-06 05:42 UTC, sodalite1204 commented on src/pages/Menu/Components/ProductSpec/ProductSpec.scss
> +                margin: 40px 0 14px 0;
```suggestion
                margin: 40px 0 14px ;
```
로도 쓸 수 있습니다.

2022-04-06 05:42 UTC, sodalite1204 commented on src/pages/Menu/Components/ProductSpec/ProductSpec.js
> +  if (!detail) return null;
이부분은 return 문에서 조건부 랜더링 잘 활용해 주시면 될 것 같네요. 
detail 데이터에 따라서 범위 잘 지정해 주시면 될 것 같습니다.
```jsx
   {detail && (
              <div className="viewCont">
                <MenuDetail detail={detail} />
                <Quantity />
                <Allergy />
                <Country />
              </div>
            )}
```

2022-04-06 05:42 UTC, sodalite1204 commented on src/pages/Menu/MenuList/MenuBox.js
> +      {category.map(data => {
매개변수 이름이 data 면 광범위하네요. 매개변수만 봐도 어떤 데이터인지 알 수 있게 네이밍해주세요:)

2022-04-06 05:42 UTC, sodalite1204 commented on src/pages/Menu/Components/Aside/Aside.js
> +  const fetchData = () => {
상품 메뉴 같은 경우에는 상수데이터가 더 적합할 것 같네요 :) 
fetch 로 사용 데이터 === DB(백)에서 받아올 데이터
상수 데이터 === 바뀌는 빈도가 낮은 프론트에서 관리하는 데이터
로 분리해서 생각하지면 좀 더 감이 오지 않을까 합니다!

2022-04-06 05:42 UTC, sodalite1204 commented on src/pages/Menu/Components/Card/Card.js
> +      {product.map(data => {
매개변수 이름이 data 면 광범위하네요. 매개변수만 봐도 어떤 데이터인지 알 수 있게 네이밍해주세요:)
데이터가 많지 않다면 매개변수자리에서 바로 구조분해 할당해주세요!

2022-04-06 05:42 UTC, sodalite1204 commented on src/pages/Menu/Components/CategoryList/Item.js
> +const Item = props => {
```suggestion
const Item = ({categoryItem}) => {
```
구조분해 할당!

2022-04-06 05:42 UTC, sodalite1204 commented on src/pages/Menu/Components/ProductSpec/Components/MenuDetail.js
> +  const [totalPrice, setTotalPrice] = useState(price);
이부분은 price 로 계산이 가능할 것 같은데 따로 두신 이유가 있나요?

2022-04-06 05:42 UTC, sodalite1204 commented on src/pages/Menu/Components/ProductSpec/Components/MenuDetail.js
> +  };
check 된 true false 에 따라 합계 금액 구하는 거면
```jsx
const optionPrice = 300
const totalPrice = price + (isCheckbox&&optionPrice);
```
로 구할 수 있을 것 같네요!

2022-04-06 07:50 UTC, charile1 commented on src/pages/Menu/Components/ProductSpec/ProductSpec.js
> +  const params = useParams();
삭제완료

2022-04-06 07:50 UTC, charile1 commented on src/pages/Menu/Components/Card/Card.js
> +  const { product } = props;
넵 수정하였습니다 !

2022-04-06 07:50 UTC, charile1 commented on src/pages/Menu/Components/Card/Card.js
> +      {product.map(data => {
넵 수정하였습니다!

2022-04-06 07:50 UTC, charile1 commented on src/pages/Menu/Components/Card/Card.js
> +                });
넵 맞습니다! params에 대해 잘 모를때 작성하고 빼지 않은 것 같습니다.

2022-04-06 07:50 UTC, charile1 commented on src/pages/Menu/Components/CategoryList/Item.js
> +const Item = props => {
수정하였습니다!

2022-04-06 07:50 UTC, charile1 commented on src/pages/Menu/Components/ProductSpec/Components/MenuDetail.js
> +  };
넵 totalprice state 삭제하고 수정하였습니다 ! addPrice 같은 경우에는 원래 default인 0에서 true false에 따라 300원이 추가되어야하기 때문에 state로 놔뒀습니다..!

2022-04-06 07:50 UTC, charile1 commented on src/pages/Menu/Components/ProductSpec/ProductSpec.js
> +  const params = useParams();
아핫 ..! 생각치도 못했습니당 !!!!

2022-04-06 07:50 UTC, charile1 commented on src/pages/Menu/Components/ProductSpec/ProductSpec.js
> +  if (!detail) return null;
조건부 렌더링으로 해결 완료하였습니다!

2022-04-06 07:50 UTC, charile1 commented on src/pages/Menu/Components/ProductSpec/ProductSpec.js
> +                </a>
a 태그가 남아있었다니... 수정하였습니다!

2022-04-06 07:50 UTC, charile1 commented on src/pages/Menu/Components/ProductSpec/ProductSpec.scss
> +                margin: 40px 0 14px 0;
> 수정하였습니다!

2022-04-06 07:50 UTC, charile1 commented on src/pages/Menu/MenuList/MenuBox.js
> +      {category.map(data => {
넵 수정하였습니당!~

2022-04-06 07:50 UTC, charile1 commented on src/pages/Menu/Components/Aside/Aside.js
> +  const fetchData = () => {
상수데이터 썼다가 디비데이터 써야하는건가..? 하고 mock으로 만들었었는데 다시 수정을 안했었습니다 !! 다시 상수데이터로 만들어서 수정하였습니다~!

2022-04-06 07:55 UTC, charile1 commented on src/pages/Menu/Components/Aside/Aside.scss
> +    // min-height: 400px;
넵 삭제하였습니다!

2022-04-06 07:56 UTC, charile1 commented on src/pages/Menu/Components/ProductSpec/ProductSpec.js
> +import { useParams, useNavigate, Link } from 'react-router-dom';
삭제완료

2022-04-06 10:42 UTC, sodalite1204 reviewed
리뷰 반영해주세요:)

2022-04-06 10:42 UTC, sodalite1204 commented on src/pages/Menu/Components/Aside/Aside.scss
> +.menuBox .leftWrap {
.leftWrap으로 시작하기 때문에 .menuBox는 불필요할 것 같습니다~

2022-04-06 10:42 UTC, sodalite1204 commented on src/pages/Menu/Components/Aside/CategoryList/CategoryList.js
> +  const { categoryList } = props;
이전부분에서 놓쳤나보네요! 이부분도 매개변수자리에서 구조분해 할당 해주세요!

2022-04-06 10:42 UTC, sodalite1204 commented on src/pages/Menu/Components/Aside/CategoryList/CategoryList.js
> +    <li className="child">
상위 클래스 네임 === 컴포넌트 이름

2022-04-06 10:42 UTC, sodalite1204 commented on src/pages/Menu/Components/Aside/CategoryList/CategoryList.js
> +        })}
```suggestion
      {categoryList &&
        categoryList.map(({id, categoryItem}) => 
         (  <Item
              key={id}
              categoryItem={categoryItem}
            />
          ))}
```
로 깔끔하게 바꿀 수 있습니다~

2022-04-06 10:42 UTC, sodalite1204 commented on src/pages/Menu/Components/Aside/CategoryList/CategoryList.scss
> +.child {
CategoryList.js 클래스명 수정시 같이 수정해주세요!

2022-04-06 10:42 UTC, sodalite1204 commented on src/pages/Menu/Components/Aside/CategoryList/Item.js
> +    <div className="childItems" onClick={goToSpec}>
컴포넌트 === 상위 클래스명

2022-04-06 10:42 UTC, sodalite1204 commented on src/pages/Menu/Components/Aside/CategoryList/Item.scss
> +.childItems {
컴포넌트명 === 상위 클래스명

2022-04-06 10:42 UTC, sodalite1204 commented on src/pages/Menu/Components/Card/Card.js
> +    <ul className="menulistBox">
컴포넌트 명 === 상위클래스명

2022-04-06 10:42 UTC, sodalite1204 commented on src/pages/Menu/Components/Card/Card.scss
> +.listWrap .menulistBox .item {
컴포넌트 ===상위 클래스명
불필요한 클래스는 삭제!

2022-04-06 10:42 UTC, sodalite1204 commented on src/pages/Menu/Components/MenuBox/MenuBox.js
> +    <article className="listWrap">
컴포넌트 명 ===상위 클래스명

2022-04-06 10:42 UTC, sodalite1204 commented on src/pages/Menu/Components/MenuBox/MenuBox.scss
> +.menuBox {
컴포넌트 명 ===상위 클래스명

2022-04-06 10:42 UTC, sodalite1204 commented on src/pages/Menu/Components/ProductSpec/Components/MenuDetail.js
> +  };
경서님 이거 제가 위에 리뷰 드린 부분에 포함되는 내용이에요.
(isCheckbox && optionPrice 자체가
isChecktbox? 300: 0 입니다.
그렇게 때문에 addPrice의 state는 필요없다는 말이였답니다! 이해 안가셨음 말씀주세요!

2022-04-07 04:53 UTC, sodalite1204 commented
경서님 수고하셨습니다☺️

2022-04-07 04:54 UTC, merged