[31기 이근휘] Add: Join페이지 레이아웃 및 기능구현
wecode-bootcamp-korea/31-1st-Dont-SOT-frontend pull request #7
Opened 2022-04-02 13:19 UTC by Geuni620

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

- 메인페이지 레이아웃
- 백엔드와 통신
- 중복확인 버튼 및 기능 구현
- 하나라도 빈 값일 시 '가입하기' 버튼 비활성화
- 비밀번호와 비밀번호 확인이 같지 않을 경우 alert 띄우기
- 중복확인버튼 누르지 않고 가입하기 버튼 누를 시 alert 띄우기

---

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

- 백엔드와의 통신
  - fetch를 통해 백엔드로 데이터를 전달하고, 그에 맞는 메세지를 읽어 alert를 사용자에게 띄워주도록 함.
- 중복확인 버튼 클릭 하지 않았을 시 버튼이 false로 변경되지 않게 했고, 이로인해 가입하기 버튼이 비활성화상태에서 풀리지 않도록 구현.
- 하나라도 빈 값일 때 가입하기 버튼을 누르지 못하도록 비활성화 구현
- 비밀번호와 비밀번호 확인이 같지 않을 경우 alert가 떠서 사용자에게 메세지를 전달하도록 구현
- 반복되는 input은 component화 했고, 상수데이터를 만들어 map으로 구현
- 가입하기 버튼 활성화 될 시, 색상 변경

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

- 레이아웃

  - 메인페이지 레이아웃 중 `dt dd dl` 태그를 처음 사용해봤는데, 많이 생소했습니다. 평소 `flex-wrap`을 잘 사용하지 않았는데, 이번 기회에 사용해볼 수 있었고, 팀원의 도움으로 알게된 `line-height`를 통해 flex의 align-item보다 더 정확하게 가운데 정렬을 할 수 있고는 사실도 알게 됐습니다.
  - `calc()`에 대해서도 알게 됐습니다. 중복확인 button의 width를 조정할 때 남는 공간을 계산해서 지정해주니 깔끔하게 떨어졌습니다.

    <br>

- 백엔드와의 통신(유효성검사)

  - 유효성 검사시 고려해야할 조건이 많아서 머리가 아팠습니다. 최대한 막아보려고했는데 아마 지금도 많이 허술한 것 같습니다. 그래도 중복확인버튼과 가입하기 버튼의 스위치용 true & false를 만들어 false일 때 버튼이 활성화 되도록 구현했습니다.

  <br />

## :: 기타 질문 및 특이 사항

- 백엔드쪽에 데이터를 전달하고 alert창을 띄우는데, 초기엔 if문의 조건으로 status를 사용했습니다. 하지만 message로 변경했어요. status를 사용했을 땐 if안에 조건문이 status를 잘 읽지 못했습니다.

- alert창을 하나씩 띄우고 싶은데 비밀번호 확인은 front에서 구현했고 나머지는 back에서 메세지를 받아서 alert를 띄우다보니 두 상황이 동시에 일어났을 때 alert창이 둘 다 뜨는 현상이 발생했습니다.

  - switch 문을 사용해서 우선순위를 case별로 구분하는게 어떨까 싶습니다.

- 백엔드 메시지 중 key error 메시지를 읽지 못하는 현상이 발생했습니다. 백엔드와 대화를 통해 '모든 값이 기입되지 않았을 시 key error 메시지가 뜬다'는 사실을 알게 됐고, front에서 모든 값이 빈 값이면 button 비활성화로 대체했습니다.

<br>

- 마지막으로, 시간이 부족해서 못했던 것은 다음과 같습니다.

1.  최근 세션을 통해 배운 회원가입 및 로그인 모달창으로 구현
2.  아이디 또는 비밀번호 형식이 맞지 않을 시 그때그때 input창 아래 메시지 전달하기

2022-04-05 05:28 UTC, younuk23 requested changes
근휘님 PR 본문 상세하게 잘 쓰신 것 너무 좋네요!!

지금 하시는 것처럼 정리하고 생각하면서 개발하시면 지금처럼 실력 계속 느실 것 같습니다!👍

Conflict가 발생해있어서 변경사항을 확인하기 어렵네요, 컨플릭 해결해주시면 다시 리뷰 보겠습니다!

2022-04-05 08:18 UTC, Geuni620 commented
> 근휘님 PR 본문 상세하게 잘 쓰신 것 너무 좋네요!!
> 
> 지금 하시는 것처럼 정리하고 생각하면서 개발하시면 지금처럼 실력 계속 느실 것 같습니다!👍
> 
> Conflict가 발생해있어서 변경사항을 확인하기 어렵네요, 컨플릭 해결해주시면 다시 리뷰 보겠습니다!

2022-04-06 06:10 UTC, sodalite1204 reviewed
리뷰 반영해주세요 그니님☺️☺️

2022-04-06 06:10 UTC, sodalite1204 commented on src/pages/Join/Form/FormInputs.js
> +          {isBtnVaild ? <button onClick={checkId}>중복확인</button> : null}
```suggestion
          {isBtnVaild && <button onClick={checkId}>중복확인</button> }
```

2022-04-06 06:10 UTC, sodalite1204 commented on src/pages/Join/Join.js
> +  const [handleDupId, setHandleDupId] = useState(false);
hooks 선언부는 컴포넌트 최상단에서 모아서 관리하시는 게 관심사의 분리 측면에서 깔끔할 것 같습니다!

2022-04-06 06:10 UTC, sodalite1204 commented on src/pages/Join/Join.js
> +                className={!isEmptyValueError ? 'active' : null}
```suggestion
                className={!isEmptyValueError && 'active' }
```

2022-04-06 06:10 UTC, sodalite1204 commented on src/pages/Join/Join.js
> +import API from '../../config';
import 순서 컨벤션!

2022-04-06 06:10 UTC, sodalite1204 commented on src/pages/Join/Form/Form.js
> +      })}
map LGTM👍

2022-04-06 06:10 UTC, sodalite1204 commented on src/pages/Join/Form/FormInputs.js
> +      <dl className="fst">
fst 는 무슨 뜻이죠? 의미가 있는 클래스명인가요?

2022-04-06 06:10 UTC, sodalite1204 commented on src/pages/Join/Form/FormInputs.js
> +          />
data.title, data.name 등은 구조분해 할당해주면 더 깔끔해집니다!
cosnt {title, name, type,placeholder} =data;

2022-04-07 05:49 UTC, sodalite1204 reviewed
훨씬 코드가 깔끔해졌네요 그니님! 리뷰 반영해주세요 :)

2022-04-07 05:49 UTC, sodalite1204 commented on src/pages/Join/Form/FormInputs.js
> +        {isIdVaild ? <button onClick={checkId}>중복확인</button> : null}
```suggestion
        {isIdVaild && <button onClick={checkId}>중복확인</button> }
```

2022-04-07 05:49 UTC, sodalite1204 commented on src/pages/Join/Form/FormInputs.js
> +        )}
중첩 삼항연산자는 오히려 가독성이 떨어집니다.
`!isIdVaild`는 boolean값만 나올긋 한데 적어주신 이유가 있을까요?
이 코드의 의도 한번만 설명해주시겠어요?

2022-04-07 05:49 UTC, sodalite1204 commented on src/pages/Join/Join.js
> +            break;
your effort 👍

2022-04-07 05:49 UTC, sodalite1204 commented on src/pages/Join/Join.js
> +            navigate('/menu');
훨씬 깔끔하네요! LGTM 👍

2022-04-07 06:23 UTC, sodalite1204 commented
그니님의 눈부신 성장 :) 수고하셨습니다☺️

2022-04-07 06:23 UTC, merged